/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rumoif.view;

/**
 *
 * @author ADMIN
 */
public class DiretorAluno extends javax.swing.JFrame {

    /**
     * Creates new form DiretorSProfessor
     */
    public DiretorAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Matéria = new javax.swing.JButton();
        jbRemover = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbAdicionar = new javax.swing.JButton();
        Imagem = new javax.swing.JLabel();
        jbVoltar = new javax.swing.JButton();
        Matéria1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Matéria.setBackground(new java.awt.Color(0, 102, 0));
        Matéria.setFont(new java.awt.Font("League Spartan", 1, 36)); // NOI18N
        Matéria.setForeground(new java.awt.Color(255, 255, 255));
        Matéria.setText("Matéria");
        Matéria.setToolTipText("");
        Matéria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Matéria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatériaActionPerformed(evt);
            }
        });
        getContentPane().add(Matéria, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 220, 60));

        jbRemover.setBackground(new java.awt.Color(0, 102, 0));
        jbRemover.setFont(new java.awt.Font("League Spartan", 1, 36)); // NOI18N
        jbRemover.setForeground(new java.awt.Color(255, 255, 255));
        jbRemover.setText("Remover");
        jbRemover.setToolTipText("");
        jbRemover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRemoverActionPerformed(evt);
            }
        });
        getContentPane().add(jbRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 220, 60));

        jbEditar.setBackground(new java.awt.Color(0, 102, 0));
        jbEditar.setFont(new java.awt.Font("League Spartan", 1, 36)); // NOI18N
        jbEditar.setForeground(new java.awt.Color(255, 255, 255));
        jbEditar.setText("Editar");
        jbEditar.setToolTipText("");
        jbEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jbEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 220, 60));

        jbAdicionar.setBackground(new java.awt.Color(0, 102, 0));
        jbAdicionar.setFont(new java.awt.Font("League Spartan", 1, 36)); // NOI18N
        jbAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        jbAdicionar.setText("Adicionar");
        jbAdicionar.setToolTipText("");
        jbAdicionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(jbAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 333, 220, 60));

        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rumoif/resources/DiretorAluno.png"))); // NOI18N
        getContentPane().add(Imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jbVoltar.setText("jButton1");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jbVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 150, 40));

        Matéria1.setBackground(new java.awt.Color(0, 102, 0));
        Matéria1.setFont(new java.awt.Font("League Spartan", 1, 36)); // NOI18N
        Matéria1.setForeground(new java.awt.Color(255, 255, 255));
        Matéria1.setText("Matéria");
        Matéria1.setToolTipText("");
        Matéria1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Matéria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Matéria1ActionPerformed(evt);
            }
        });
        getContentPane().add(Matéria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 220, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        DiretorAlunoAdicionar d = new DiretorAlunoAdicionar();
        d.setVisible(true);
    }//GEN-LAST:event_jbAdicionarActionPerformed

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        DiretorS d = new DiretorS();
        d.setVisible(true);
    }//GEN-LAST:event_jbVoltarActionPerformed

    private void jbRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverActionPerformed
        // TODO add your handling code here
        this.dispose();
        DiretorAlunoRemover d = new DiretorAlunoRemover();
        d.setVisible(true);
    }//GEN-LAST:event_jbRemoverActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        DiretorAlunoEditar d = new DiretorAlunoEditar();
        d.setVisible(true);
    }//GEN-LAST:event_jbEditarActionPerformed

    private void MatériaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatériaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        DiretorAlunoMateria d = new DiretorAlunoMateria();
        d.setVisible(true);
    }//GEN-LAST:event_MatériaActionPerformed

    private void Matéria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Matéria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Matéria1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiretorAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiretorAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiretorAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiretorAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiretorAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton Matéria;
    private javax.swing.JButton Matéria1;
    private javax.swing.JButton jbAdicionar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbRemover;
    private javax.swing.JButton jbVoltar;
    // End of variables declaration//GEN-END:variables
}
