/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rumoif.view;

import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import rumoif.control.LoginController;
import java.sql.*;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import rumoif.model.dao.LoginDAO;

/**
 *
 * @author Caiqu
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public Login() {
        initComponents();
        jtUsuario.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    fazerLogin();
                }
            }
        });

        jpSenha.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    fazerLogin();
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtUsuario = new javax.swing.JTextField();
        jpSenha = new javax.swing.JPasswordField();
        jbEntrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtUsuario.setFont(new java.awt.Font("League Spartan", 0, 14)); // NOI18N
        jtUsuario.setCaretColor(new java.awt.Color(70, 73, 75));
        jtUsuario.setDisabledTextColor(new java.awt.Color(70, 73, 75));
        jtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jtUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtUsuarioMouseExited(evt);
            }
        });
        getContentPane().add(jtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 230, 30));

        jpSenha.setFont(new java.awt.Font("League Spartan", 0, 14)); // NOI18N
        getContentPane().add(jpSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 230, 30));

        jbEntrar.setBackground(new java.awt.Color(255, 204, 0));
        jbEntrar.setFont(new java.awt.Font("Glacial Indifference", 1, 14)); // NOI18N
        jbEntrar.setForeground(new java.awt.Color(51, 51, 51));
        jbEntrar.setText("Entrar");
        jbEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbEntrarMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbEntrarMouseReleased(evt);
            }
        });
        jbEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEntrarActionPerformed(evt);
            }
        });
        jbEntrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbEntrarKeyPressed(evt);
            }
        });
        getContentPane().add(jbEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rumoif/resources/Login.png"))); // NOI18N
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jLabel1KeyTyped(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fazerLogin() {
        if (jtUsuario.getText().isEmpty() || jpSenha.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!", "Preencha todos os campos", JOptionPane.HEIGHT);
        } else {
            try {
                LoginController login = new LoginController();

                switch (login.loginUsuario(this)) {
                    case 0:
                        this.dispose();
                        AlunoMateria a = new AlunoMateria(login.nomeAluno(this));
                        a.setVisible(true);
                        break;
                    case 1:
                        ProfessorS p = new ProfessorS(login.nomeProfessor(this));
                        p.setVisible(true);
                        this.dispose();

                        break;

                    case 2:
                        this.dispose();
                        DiretorS d = new DiretorS();
                        d.setVisible(true);
                        break;
                    default:
                        JOptionPane.showMessageDialog(this, "ERRO! Usuário ou senha incorretos!", "Erro de Login!", JOptionPane.YES_OPTION);
                        break;
                }
            } catch (SQLException sql) {
                // Tratamento de exceção
            }
        }
    }
    private void jbEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEntrarActionPerformed
        // TODO add your handling code here:
        fazerLogin();


    }//GEN-LAST:event_jbEntrarActionPerformed

    private void jLabel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyPressed

    }//GEN-LAST:event_jLabel1KeyPressed

    private void jLabel1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1KeyTyped

    private void jbEntrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbEntrarKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jbEntrarKeyPressed

    private void jbEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbEntrarMouseEntered
        // TODO add your handling code here:
        jbEntrar.setBackground(new Color(140, 112, 0));
    }//GEN-LAST:event_jbEntrarMouseEntered

    private void jbEntrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbEntrarMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jbEntrarMouseReleased

    private void jbEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbEntrarMouseExited
        // TODO add your handling code here:
        jbEntrar.setBackground(new Color(255, 204, 0));
    }//GEN-LAST:event_jbEntrarMouseExited

    private void jtUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtUsuarioMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jtUsuarioMouseEntered

    private void jtUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtUsuarioMouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_jtUsuarioMouseExited

    public JButton getjButton1() {
        return jbEntrar;
    }

    public void setjButton1(JButton jButton1) {
        this.jbEntrar = jButton1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JPasswordField getjPasswordField1() {
        return jpSenha;
    }

    public void setjPasswordField1(JPasswordField jPasswordField1) {
        this.jpSenha = jPasswordField1;
    }

    public JTextField getjTextField1() {
        return jtUsuario;
    }

    public void setjTextField1(JTextField jTextField1) {
        this.jtUsuario = jTextField1;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbEntrar;
    private javax.swing.JPasswordField jpSenha;
    private javax.swing.JTextField jtUsuario;
    // End of variables declaration//GEN-END:variables
}
