/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rumoif.view;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import rumoif.model.bean.Materia;
import rumoif.model.bean.Professor;
import rumoif.model.dao.MateriaDAO;
import rumoif.model.dao.ProfessorMateriaDAO;

/**
 *
 * @author ADMIN
 */
public class ProfessorS extends javax.swing.JFrame {

    /**
     * Creates new form ProfessorScreen
     */
    static Professor professor;

    public ProfessorS(Professor professor) {
        initComponents();
        this.professor = professor;
        preencherComboBox();
        jNome.setText(professor.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNome = new javax.swing.JLabel();
        Selecionar = new javax.swing.JButton();
        jlista = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        IMAGEM = new javax.swing.JLabel();
        jvoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jNome.setFont(new java.awt.Font("League Spartan ExtraBold", 0, 36)); // NOI18N
        jNome.setForeground(new java.awt.Color(255, 255, 255));
        jNome.setText("Caique Augusto");
        getContentPane().add(jNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        Selecionar.setBackground(new java.awt.Color(102, 102, 102));
        Selecionar.setFont(new java.awt.Font("League Spartan ExtraBold", 0, 18)); // NOI18N
        Selecionar.setForeground(new java.awt.Color(255, 255, 255));
        Selecionar.setText("Selecionar");
        Selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelecionarActionPerformed(evt);
            }
        });
        getContentPane().add(Selecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 290, 30));

        jlista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jlista.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlistaActionPerformed(evt);
            }
        });
        getContentPane().add(jlista, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 290, -1));

        jLabel1.setFont(new java.awt.Font("League Spartan ExtraBold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Matéria");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        IMAGEM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rumoif/resources/Professor.png"))); // NOI18N
        getContentPane().add(IMAGEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jvoltar.setText("voltar");
        jvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jvoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jvoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 500, 150, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void preencherComboBox() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(); // Modelo para o JComboBox

        // Recupere os dados do banco de dados usando o DAO (substitua isso pelo seu código)
        List<Materia> itensDoBanco = new ProfessorMateriaDAO().readUnit(professor);

        // Adicione os itens da lista ao modelo do JComboBox
        for (Materia item : itensDoBanco) {
            model.addElement(item.getNome_materia());
        }

        jlista.setModel(model); // Atribua o modelo ao JComboBox
    }
    
    private Materia pegarMateria(String item) {
        MateriaDAO materiaDAO = new MateriaDAO();
        Materia materia = materiaDAO.read(item);
        return materia;
    }
    
    private void SelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelecionarActionPerformed
        // TODO add your handling code here:

        ProfessorMateria tela = new ProfessorMateria(pegarMateria((String)jlista.getSelectedItem()), professor);
        this.dispose();
        tela.setVisible(true);
    }//GEN-LAST:event_SelecionarActionPerformed

    private void jlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlistaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jlistaActionPerformed

    private void jvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jvoltarActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jvoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfessorS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfessorS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfessorS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfessorS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfessorS(professor).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IMAGEM;
    private javax.swing.JButton Selecionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jNome;
    private javax.swing.JComboBox<String> jlista;
    private javax.swing.JButton jvoltar;
    // End of variables declaration//GEN-END:variables
}
